services:
  cephylas:
    env_file:
      - .env.production

  cephylas-nextjs:
    image: daiius/private-registry:cephylas-nextjs
    container_name: cephylas-nextjs
    env_file:
      - .env.production
    volumes:
      - ./log:/app/log:ro
